### ISSUE TITLE
Component does not work

### ISSUE THREAD

**Issue by Cheaser** [alessiomaffeis/vue-picture-input#1] opened 2017-02-21 04:33 UTC
this component shows on page, but does not work, webpack2, vue2, chrome/safari
what should i do? 
i try it on new project(vue init webpack) & on my existing project:
w/ new project picture-input shows "File open dialog", but nothing actions else
w/ existing project component only shows, but dont have reaction on click and drop

it's not working :(

**Comment by alessiomaffeis** [comment] 2017-02-21 08:25
Uhm, does any error show up in the console?
By the way, is it working in the example project?

**Comment by Cheaser** [comment] 2017-02-21 12:45
no error, im confused. in example its opens file-open dialog, but after file choose component do nothing, latest version, yep.

**Comment by alessiomaffeis** [comment] 2017-02-21 14:05
Unfortunately, I can't reproduce the issue and I don't know how I can help you without any guidance from errors/warnings, so I am going to close this one.

**Closed by alessiomaffeis** 2017-02-21 14:05 UTC
