### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by LorrainInfinity** [alessiomaffeis/vue-picture-input#24] opened 2017-07-24 13:57 UTC
I guess I've done what I had to do to use this plugin, but it looks like it's not working at all.  The drag and drop box is not even showing.

**Comment by alessiomaffeis** [comment] 2017-07-24 14:04
That sounds weird. Can you give me more context/example code?

**Comment by LorrainInfinity** [comment] 2017-07-24 14:12
Well, I used it the way your example said it should be used :s.

The component is rendered but it looks like there is a style issue (I'm displaying it in a bootstrap modal by the way.  I doubt it comes from that but who knows :p).

I also noticed that if I change the style of some elements inside your component, the "dropzone" appears but it's still not useable.  No errors displayed, nothing..  I'm using the latest version of Vue.

**Comment by alessiomaffeis** [comment] 2017-07-24 14:41
Just tried with the latest version of Vue, and it seems to be working fine.
Can you please show a snippet of the code where you are using the component?

**Comment by LorrainInfinity** [comment] 2017-07-24 15:16
Ok so I installed your plugin via npm.  
I imported it and included it in my components list.
Then I just used the very same snippet of code as yours :p 

`<picture-input
                        ref="cropperInput"
                        @change="handleLoadedImage"
                        width="600"
                        height="600"
                        margin="16"
                        accept="image/jpeg,image/png"
                        size="10"
                        button-class="btn">
                    </picture-input>`

And it's not showing up.  I see it in my debugger, I see it in the DOM, but it looks like something else is going wrong it's just hidden :/

**Comment by alessiomaffeis** [comment] 2017-07-24 15:22
It could be a styling issue on your side, then. I can't reproduce it.
Have you tried it outside the modal?

**Comment by LorrainInfinity** [comment] 2017-07-24 15:26
Not really, but a funny thing just happened : I managed to get it working by ... opening a new tab in my browser and getting back on the previous one right after O_O

**Comment by alessiomaffeis** [comment] 2017-07-24 15:36
That's weird. By the way, can you please try updating vue-picture-input to 1.12.2 and check again?

**Comment by LorrainInfinity** [comment] 2017-07-25 06:57
Still no changes, that's so weird :p.  Well I guess it comes from me so you can just close the issue, I don't want people to think it's not working if it does :)

**Comment by alessiomaffeis** [comment] 2017-07-25 07:38
Yeah, I am sorry but I don't know how to help you, since I can't reproduce the issue. 
I would suggest you to check if it is an issue with z-index. In the mean time, I will close this issue.

**Closed by alessiomaffeis** 2017-07-25 07:38 UTC
