### ISSUE TITLE
the reason of "This file type is not supported."

### ISSUE THREAD

**Issue by huiminghu** [alessiomaffeis/vue-picture-input#117] opened 2019-12-14 07:34 UTC
1.
```
if (this.accept !== 'image/*') {
      this.fileTypes = this.accept.split(',')
      this.fileTypes = this.fileTypes.map(s => s.trim())
    }
```
2.
```
if (this.accept === 'image/*') {
        if (files[0].type.substr(0, 6) !== 'image/') {
          return
        }
      } else {
        if (this.fileTypes.indexOf(files[0].type) === -1) {
          this.$emit('error', {
            type: 'fileType',
            fileSize: files[0].size,
            fileType: files[0].type,
            fileName: files[0].name,
            message: this.strings.fileType
          })
          return
        }
      }

```
this two part are obviously wrong. cause if i set  accept="image/jpeg,image/png", then execute above 1 code,  this.fileTypes will convert to a array. and when execute  "if (this.fileTypes.indexOf(files[0].type) === -1) {"  of 2 code, it will lead to wrong result that is "This file type is not supported".

**Comment by alessiomaffeis** [comment] 2020-03-04 16:45
Sorry, I cannot reproduce the issue. Closing it for now.

**Closed by alessiomaffeis** 2020-03-04 16:45 UTC
