### ISSUE TITLE
Feature request: cover functionality

### ISSUE THREAD

**Issue by julianfox** [alessiomaffeis/vue-picture-input#16] opened 2017-05-04 01:47 UTC
Is it possible to implement a cover functionality (like background-size: cover) ?
I tried to implement it with this example:
https://stackoverflow.com/questions/21961839/simulation-background-size-cover-in-canvas/21961894#21961894

But I can't manage to adapt it with vue-picture-input... any idea ?

**Comment by alessiomaffeis** [comment] 2017-05-04 09:09
What do you mean? Vue-picture-input already behaves like "background-size: cover" with center positioning, when :crop="true" (default).

**Comment by julianfox** [comment] 2017-05-04 09:28
All work perfectly with large picture, but I get this issue with pictures small and in another ratio:
e.g: 
![screen shot 2017-05-04 at 4 27 19 pm](https://cloud.githubusercontent.com/assets/1648714/25697811/a2b90cd8-30e6-11e7-8369-092869431d87.png)

**Comment by alessiomaffeis** [comment] 2017-05-04 09:29
Got it, will look into that ;)

**Comment by alessiomaffeis** [comment] 2017-09-20 09:16
I can't reproduce the issue. 🤔 Any ideas?

**Comment by alessiomaffeis** [comment] 2017-11-03 10:10
I managed to reproduce it, and it seems to happen with square pictures only. 🤔 Looking into that!

**Comment by alessiomaffeis** [comment] 2017-11-03 11:25
It should be fixed in v1.18.0, try it out! Let me know if it doesn't work, and I'll reopen the issue.

**Closed by alessiomaffeis** 2017-11-03 11:25 UTC
Labels: bug
